### ISSUE TITLE
PDF manual covers

### ISSUE THREAD

**Issue by Treadmule** [DeviationTX/deviation-manual#10]
The cover pages of the PDF manuals refer to the 4.0.1 version rather than 5.0 release. Also, the date on the covers is 2015 - needs to be fixed.

**Comment by TheRealMoeder** [comment]
Corrected in commit https://github.com/DeviationTX/deviation-manual/commit/a08782c6baf3ff0c795d0caefb98d3c2aeba65a8

**Comment by F-D-R** [comment]
Yeah, but I still couldn't make the manual, so the downloadable version still has wrong version...

**Comment by TheRealMoeder** [comment]
Haven't looked into building the manual... I will spare a moment for it...

**Comment by F-D-R** [comment]
Others reported success building it, but I can't compile on either of my Windows environment, though they give me different errors...
