### ISSUE TITLE
Ja translation completed 

### ISSUE THREAD

**Issue by TheRealMoeder** [DeviationTX/deviation-manual#47]
@F-D-R @PhracturedBlue can you please add a link to the Japanese HTML manual on  deviationtx.com?

**Comment by PhracturedBlue** [comment]
I added the html page link, but I'm still trying to figure out how to update the pdf

**Comment by TheRealMoeder** [comment]
Doing ja PDF requires some work, probably a different latex processor. I already went through this trouble for Chinese, ultimately dropping it until sphinx 2.0 is released
